Repository Bajamen/BarkPoint, pull requests merged in 2020-11, with the labels that each got.

#31 (update) Feat/models
  server/db/index.js
  server/db/models/dog.js
  server/db/models/models.js
  server/db/models/toy.js
  server/db/models/user.js
Labels: database

#32 (fix) dist in .gitignore
  .gitignore
  client/dist/dundle.js
  client/dist/index.html
Labels: bug

#34 Feature/personality assessment changes
  client/dist/dundle.js
  client/src/components/App.jsx
  client/src/components/Auth.jsx
  client/src/components/GoogleLogin.jsx
  client/src/components/PersonalityAssessment.css
  client/src/components/PersonalityAssessment.jsx
  package.json
Labels: components, 📝Under Review

#37 (fix) gitignore
  .gitignore
Labels: bug, 📝Under Review

#36 (create) google strategy & sessions
  package-lock.json
  package.json
  server/db/index.js
  server/db/models/models.js
  server/db/models/toy.js
  server/db/models/user.js
  server/googleStrategy.js
  server/index.js
  server/routes/auth.router.js
Labels: routers, server, 📝Under Review

#40 (refactor) models and routes
  package-lock.json
  package.json
  server/db/models/dog.js
  server/db/models/models.js
  server/db/models/toy.js
  server/db/models/user.js
  server/routes/serpwow.js
Labels: database, 📝Under Review

#39 (Remove) dundle.js
  client/dist/dundle.js
Labels: bug, 🚩Ready for Review 🚩

#46 updates
  client/src/components/App.jsx
  client/src/components/GoogleLogin.jsx
  package-lock.json
  package.json
  server/index.js
Labels: components

#45 (create) requests for db to client comms
  server/db/index.js
  server/db/models/dog.js
  server/db/models/toy.js
  server/db/models/user.js
  server/routes/db.router.js
Labels: database, routers, server, 🚩Ready for Review 🚩

#51 (fix) bug in google strategy redirect-47
  server/db/models/dog.js
  server/db/models/user.js
  server/googleStrategy.js
  server/routes/auth.router.js
Labels: bug, 🚩Ready for Review 🚩

#54 (create) twilio configuration-#6
  package-lock.json
  package.json
  server/api/twilio.api.js
  server/index.js
  server/routes/api.router.js
Labels: api, routers, 🚩Ready for Review 🚩

#61 (fix) eslint in husky-50233988
  client/src/components/DogComp.jsx
  client/src/components/Form.jsx
  client/src/components/Profile.jsx
  client/src/components/ToyBox.jsx
  package.json
Labels: bug, 📝Under Review

#63 (doc) documentation for client
  client/helpers/helpers.js
  client/src/components/DogComp.jsx
  client/src/components/Form.jsx
  client/src/components/GoogleLogin.css
  package.json
Labels: documentation, 🚩Ready for Review 🚩

#67 (create) findDogs method
  server/db/models/dog.js
Labels: database

#68 Bug/ fixed in db routes and models
  package-lock.json
  server/db/index.js
  server/db/models/dog.js
  server/routes/db.router.js
Labels: bug, database, 📝Under Review

#74 (feat) created parks model and routes
  server/db/models/dog.js
  server/db/models/models.js
  server/db/models/park.js
  server/db/models/user.js
  server/routes/db.router.js
Labels: documentation, routers

#80 (documentation) added for park.js, user.js, and auth.router.js
  package-lock.json
  package.json
  server/db/models/park.js
  server/db/models/user.js
  server/routes/auth.router.js
Labels: documentation, 📝Under Review

#81 (fix) serpwow API filter
  server/db/models/dog.js
  server/routes/api.router.js
  server/routes/auth.router.js
  server/routes/personalityTypes.json
Labels: api, bug, server, 🚩Ready for Review 🚩
